title: "LastWish Cryptocurrency Inheritance Platform"
description: "A platform for cryptocurrency inheritance."
theme: jekyll-theme-primer
# Uncomment and edit the line below if you have a custom domain
# url: "https://your-custom-domain.com"
